// List of common words for speech and text to braille conversion
export const commonWords = [
  "hello",
  "goodbye",
  "thank you",
  "please",
  "help",
  "yes",
  "no",
  "sorry",
  "excuse me",
  "how are you",
  "I am fine",
  "good morning",
  "good afternoon",
  "good evening",
  "good night",
  "my name is",
  "nice to meet you",
  "water",
  "food",
  "bathroom",
  "emergency",
  "doctor",
  "hospital",
  "family",
  "friend",
]
